apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-suqqjsqm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-suqqjsqm 
  name: go-suqqjsqm
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-suqqjsqm
    weight: 100 
